/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : MeCab 994
 #	author : miyako
 #	2012/08/21
 #
 # --------------------------------------------------------------------------------*/



// --- MeCab
void MeCab_SET_SYSTEM_DICTIONARY(sLONG_PTR *pResult, PackagePtr pParams);
void MeCab_Get_system_dictionary(sLONG_PTR *pResult, PackagePtr pParams);
void MeCab_GET_KEYWORDS(sLONG_PTR *pResult, PackagePtr pParams);
void MeCab_GET_NODES(sLONG_PTR *pResult, PackagePtr pParams);

// --- MeCab Developer
void MeCab_CREATE_USER_DICTIONARY(sLONG_PTR *pResult, PackagePtr pParams);
